import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from './components/Nav'
import { SparklesPreview } from "./components/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
        <a href="/">
     <div className="absolute left-[10%] top-5 z-10 hidden md:block">
      <img src={"https://github.com/KarthikeyaKollu/elvsystems/assets/108949445/72da1545-4142-49c0-8e5e-36d4098fcd87"} alt=""  width={"200px"} height={"200px"}/>
     </div>
     </a>
        <NavbarDemo />
        
        {children}
        <SparklesPreview />
        
        </main>

      </body>
    </html>
  );
}
